"""
📊 PoE Ensemble Evaluation and Comparison Module
------------------------------------------------

This module facilitates the formal evaluation of Product-of-Experts (PoE)
ensemble techniques against individual local classifiers. It is designed
to generate empirical evidence and visualizations suitable for academic
rebuttals and performance verification.

🧠 Purpose:
    To provide a rigorous statistical comparison between isolated client
    models (local classifiers) and their aggregated inference (PoE),
    quantifying improvements in accuracy and calibration.

🔧 Core Functionalities:
    • Load experimental configurations and trained PyTorch models
    • Perform inference using both single-model and PoE aggregation strategies
    • Calculate comprehensive metrics (Accuracy, AUROC, F1, Precision, Recall)
    • Generate publication-ready comparative visualizations (bar charts)
    • Output statistical summaries and rebuttal snippets

🎯 Intended Use:
    • Research paper rebuttals
    • Ensemble learning performance analysis
    • Federated learning experimental validation

📁 Dependencies:
    • torch (PyTorch)
    • numpy
    • matplotlib / seaborn
    • sklearn.metrics
    • tabulate

📝 Notes:
    The module assumes a specific directory structure generated by previous
    training runs (containing `args.json` and a `models/classifiers` subdirectory).

Author: Andrea Moleri
File Location: src/utils/poe_proof.py
Last Modified: 20/11/2025
"""

import argparse
import json
import sys
import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, precision_score, recall_score
from tabulate import tabulate

# Ensure the original project modules can be imported by appending the parent directory to sys.path
sys.path.append(str(Path(__file__).parent))

try:
    from models.cnn import SimpleCNN
    from imports.data_management import get_dataset
    from imports.data_augmentation import build_transform
except ImportError as e:
    # Translated user-facing error message
    print("Import error: ensure this file is located in the 'src/' folder of the project.")
    raise e


def load_run_args(run_dir: Path) -> argparse.Namespace:
    """
    Loads the experimental arguments configuration from the args.json file.

    This function restores the exact hyperparameter and configuration context
    under which the models were originally trained, ensuring reproducibility
    during the evaluation phase.

    Args:
        run_dir (Path): The filesystem path to the specific experiment run directory.

    Returns:
        argparse.Namespace: A namespace object containing the experiment configuration.

    Raises:
        FileNotFoundError: If `args.json` does not exist in the specified directory.
    """
    args_path = run_dir / "args.json"
    if not args_path.exists():
        raise FileNotFoundError(f"args.json not found in {run_dir}")

    with open(args_path, 'r') as f:
        args_dict = json.load(f)
    return argparse.Namespace(**args_dict)


def load_classifiers(run_dir: Path, device: torch.device, num_classes: int, channels: int):
    """
    Loads all client classifier models stored within the run directory.

    This function iterates through the model directory, instantiates the
    CNN architecture, and loads the state dictionaries for every identified
    client model checkpoint.



[Image of Convolutional Neural Network architecture]


    Args:
        run_dir (Path): The root directory of the experiment run.
        device (torch.device): The computation device (CPU or CUDA) to map the models to.
        num_classes (int): The dimensionality of the output layer (number of target classes).
        channels (int): The number of input channels (e.g., 1 for grayscale, 3 for RGB).

    Returns:
        tuple: A tuple containing:
            - models (list[torch.nn.Module]): A list of loaded model instances in evaluation mode.
            - model_names (list[str]): A corresponding list of filenames (stems) for identification.

    Raises:
        ValueError: If no model files matching the pattern are discovered.
    """
    model_dir = run_dir / "models" / "classifiers"
    models = []
    model_names = []

    # Pattern matching for client-*.pt files using pathlib's glob
    for model_path in sorted(model_dir.glob("client-*.pt")):
        print(f"-> Loading {model_path.name}...")
        model = SimpleCNN(channels, num_classes).to(device)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model.eval()  # Set to evaluation mode (disables Dropout/BatchNorm updates)
        models.append(model)
        model_names.append(model_path.stem)

    if not models:
        raise ValueError(f"No models found in {model_dir}")

    return models, model_names


@torch.no_grad()
def get_predictions(models, dataloader, device):
    """
    Executes inference to generate predictions for individual models and the PoE ensemble.

    This function aggregates the logical probability distributions of multiple
    experts using the Product-of-Experts (PoE) rule.

    The PoE rule is mathematically defined in log-space as the summation of
    individual log-probabilities, which corresponds to multiplication in
    probability space:

    $$ \log P_{poe}(y|x) \propto \sum_{i} \log P_i(y|x) $$



    Args:
        models (list): A list of PyTorch models (classifiers).
        dataloader (DataLoader): Iterable for the test dataset.
        device (torch.device): Computation device.

    Returns:
        tuple:
            - y_true (np.ndarray): Ground truth labels.
            - single_probs (np.ndarray): Probabilities for each individual model.
              Shape: (Num_Models, Num_Samples, Num_Classes).
            - poe_probs (np.ndarray): Aggregated probabilities derived via PoE.
              Shape: (Num_Samples, Num_Classes).
    """
    all_y_true = []
    # Accumulator structure for raw logits: list of lists (concatenated later)
    # single_logits_accum[model_idx] = [tensor_batch_1, tensor_batch_2...]
    single_logits_accum = [[] for _ in models]

    print("Running inference on the Test Set...")
    for x, y in dataloader:
        x = x.to(device)
        all_y_true.append(y.cpu())

        # Iterate through every loaded expert model
        for i, model in enumerate(models):
            logits = model(x)  # Shape: (Batch_Size, Num_Classes)
            single_logits_accum[i].append(logits.cpu())

    y_true = torch.cat(all_y_true).numpy()

    # Concatenate all batches for each model to form full dataset logits
    # single_logits_all final shape: (Num_Models, Total_Samples, Num_Classes)
    single_logits_all = []
    for i in range(len(models)):
        single_logits_all.append(torch.cat(single_logits_accum[i], dim=0))

    single_logits_all = torch.stack(single_logits_all)

    # --- 1. Calculation of Individual Probabilities ---
    # Apply Softmax to convert raw logits to probabilities for each model independently
    single_probs = torch.softmax(single_logits_all, dim=2).numpy()

    # --- 2. Calculation of Product of Experts (PoE) ---
    # Formula: log P_poe(y|x) = sum(log P_i(y|x)) + const
    #          P_poe(y|x) = Softmax( sum(LogSoftmax(logits_i)) )

    epsilon = 1e-12
    # Use LogSoftmax for numerical stability compared to log(softmax)
    log_probs_all = torch.log_softmax(single_logits_all, dim=2)

    # Summation of log-probabilities (equivalent to product of probabilities)
    poe_logits = torch.sum(log_probs_all, dim=0)

    # Final Softmax to obtain the normalized probability distribution for the ensemble
    poe_probs = torch.softmax(poe_logits, dim=1).numpy()

    return y_true, single_probs, poe_probs


def compute_metrics(y_true, probs):
    """
    Calculates a suite of standard classification performance metrics.



    Args:
        y_true (np.ndarray): Ground truth integer labels.
        probs (np.ndarray): Predicted class probabilities of shape (N, C).

    Returns:
        dict: A dictionary containing 'Accuracy', 'AUROC', 'Precision',
              'Recall', and 'F1-Score'.
    """
    preds = np.argmax(probs, axis=1)
    acc = accuracy_score(y_true, preds)

    # Handle AUROC calculation for both binary and multiclass scenarios
    try:
        if probs.shape[1] > 2:
            # 'ovr' (One-vs-Rest) strategy for multiclass AUC
            auroc = roc_auc_score(y_true, probs, multi_class='ovr', average='macro')
        else:
            # For binary cases, we typically pass the probability of the positive class (index 1)
            auroc = roc_auc_score(y_true, probs[:, 1])
    except ValueError:
        # Fallback if a batch is missing specific classes, preventing a crash
        auroc = 0.0

    # Use 'macro' averaging to treat all classes equally regardless of imbalance
    precision = precision_score(y_true, preds, average='macro', zero_division=0)
    recall = recall_score(y_true, preds, average='macro', zero_division=0)
    f1 = f1_score(y_true, preds, average='macro', zero_division=0)

    return {
        "Accuracy": acc,
        "AUROC": auroc,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1
    }


def plot_comparison(results, output_path):
    """
    Generates a high-quality, publication-ready bar chart comparing model performance.

    Visualizes the performance gap between the Average Local Classifier,
    the Best Single Local Classifier, and the PoE Ensemble.

    Args:
        results (dict): A nested dictionary containing metric scores for each method.
        output_path (Path): The filesystem path where the plot image will be saved.

    Returns:
        None
    """
    metrics = ["Accuracy", "AUROC", "F1-Score"]

    # Data extraction
    poe_scores = [results["PoE"][m] for m in metrics]
    avg_local = [results["Average Local"][m] for m in metrics]
    best_local = [results["Best Single"][m] for m in metrics]

    x = np.arange(len(metrics))
    width = 0.25

    plt.figure(figsize=(10, 6))
    sns.set_style("whitegrid")

    # Plotting bars with distinct, professional colors
    plt.bar(x - width, avg_local, width, label='Avg Local Classifier', color='#A9A9A9')  # Dark Gray
    plt.bar(x, best_local, width, label='Best Single Local', color='#4682B4')  # Steel Blue
    plt.bar(x + width, poe_scores, width, label='PoE Ensemble (Ours)', color='#DC143C')  # Crimson

    plt.ylabel('Score')
    plt.title('Empirical Justification: PoE Ensemble vs Local Classifiers')
    plt.xticks(x, metrics)
    plt.ylim(0, 1.1)
    plt.legend()

    # Annotate bars with exact values for clarity
    for i, v in enumerate(poe_scores):
        plt.text(i + width, v + 0.02, f"{v:.3f}", ha='center', fontweight='bold')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    print(f"\n[PLOT] Chart saved to: {output_path}")


def main():
    """
    Main execution entry point for the PoE formal proof generation.

    Orchestrates the data loading, model instantiation, inference,
    metric calculation, and reporting processes.
    """
    parser = argparse.ArgumentParser(description="Generates formal PoE vs Local proof for Rebuttal")
    parser.add_argument("--run-dir", type=str, required=True,
                        help="Path to the run directory (e.g., output/.../run_xxx)")
    parser.add_argument("--batch-size", type=int, default=256)
    args = parser.parse_args()

    run_dir = Path(args.run_dir)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 1. Setup
    print(f"--- Starting PoE Formal Proof ---")
    print(f"Run Directory: {run_dir}")

    run_args = load_run_args(run_dir)
    print(f"Original Dataset: {run_args.dataset}")

    # 2. Data Loading (Mirrors logic in main.py for consistency)
    # Note: prime_dataset_meta_for_transform might be needed if used in the original main
    # here we assume standard transform usage.
    tfm = build_transform(run_args.dataset)

    # Load Test Set
    test_set = get_dataset(run_args.dataset, run_args.data_dir, train=False, transform=tfm)

    # Dataset Information retrieval
    try:
        num_classes = len(test_set.classes)
    except:
        num_classes = len(set(test_set.targets if hasattr(test_set, 'targets') else test_set.labels))

    sample_img, _ = test_set[0]
    channels = sample_img.shape[0]

    test_loader = DataLoader(test_set, batch_size=args.batch_size, shuffle=False, num_workers=4)

    # 3. Load Models
    models, model_names = load_classifiers(run_dir, device, num_classes, channels)
    print(f"Found {len(models)} local classifiers.")

    # 4. Inference
    y_true, single_probs_list, poe_probs = get_predictions(models, test_loader, device)

    # 5. Metric Calculation
    results = {}

    # A) Metrics for every single client
    single_metrics_list = []
    for i, name in enumerate(model_names):
        m = compute_metrics(y_true, single_probs_list[i])
        m['Model'] = name
        results[name] = m
        single_metrics_list.append(m)

    # B) PoE Metrics
    poe_metrics = compute_metrics(y_true, poe_probs)
    results["PoE"] = poe_metrics

    # C) Statistical Aggregates
    avg_local = {}
    best_local = {}  # Best based on Accuracy

    metric_keys = ["Accuracy", "AUROC", "Precision", "Recall", "F1-Score"]

    # Calculate average performance across local models
    for k in metric_keys:
        vals = [sm[k] for sm in single_metrics_list]
        avg_local[k] = np.mean(vals)

    # Identify the single best model based on Accuracy
    best_acc = -1
    best_model_idx = -1

    for i, sm in enumerate(single_metrics_list):
        if sm["Accuracy"] > best_acc:
            best_acc = sm["Accuracy"]
            best_model_idx = i

    best_local = single_metrics_list[best_model_idx].copy()
    del best_local['Model']

    results["Average Local"] = avg_local
    results["Best Single"] = best_local

    # 6. Tabular Visualization
    table_data = []
    # Rows for individual models
    for sm in single_metrics_list:
        row = [sm['Model']] + [f"{sm[k]:.4f}" for k in metric_keys]
        table_data.append(row)

    # Separator line
    table_data.append(["-" * 10] + ["-" * 6] * len(metric_keys))

    # Summary rows
    table_data.append(["AVG Local"] + [f"{avg_local[k]:.4f}" for k in metric_keys])
    table_data.append([f"BEST Local ({model_names[best_model_idx]})"] + [f"{best_local[k]:.4f}" for k in metric_keys])
    table_data.append(["PoE (Ensemble)"] + [f"{poe_metrics[k]:.4f}" for k in metric_keys])

    print("\n" + tabulate(table_data, headers=["Model"] + metric_keys, tablefmt="github"))

    # 7. Plot Generation and Saving
    output_plot = run_dir / "poe_comparison_rebuttal.png"
    plot_comparison(results, output_plot)

    # 8. Textual Output for Rebuttal
    gain_acc = poe_metrics['Accuracy'] - avg_local['Accuracy']
    gain_auroc = poe_metrics['AUROC'] - avg_local['AUROC']

    print("\n--- REBUTTAL SNIPPET SUGGESTION ---")
    print(
        f"\"Empirical results on {run_args.dataset} demonstrate the efficacy of the Product-of-Experts (PoE) aggregation.")
    print(f"While individual local classifiers achieve an average accuracy of {avg_local['Accuracy']:.1%}, "
          f"the PoE ensemble reaches {poe_metrics['Accuracy']:.1%}, representing a significant performance gain of +{gain_acc * 100:.1f} percentage points.")
    print(
        f"Furthermore, PoE improves the AUROC from {avg_local['AUROC']:.3f} (avg local) to {poe_metrics['AUROC']:.3f}, "
        f"confirming that the multiplicative aggregation successfully suppresses high-confidence errors from individual diverse experts.\"")


if __name__ == "__main__":
    main()